FROM node:16-alpine as develop

ENV ROOT=/usr/src/app

WORKDIR ${ROOT}

RUN apk update && apk upgrade --available

COPY ./client/package*.json .
RUN npm install
COPY ./client .

CMD [ "npm", "run", "dev:ssr" ]
