version: '3.9'
services:
  client:
    container_name: client
    build:
      context: .
      dockerfile: ./client/dockerfile
      target: develop
    tty: true
    restart: "always"
    ports:
      - "4200:4200"
    working_dir: /usr/src/app
    volumes:
      - "./client:/usr/src/app"
      - clientdependency:/usr/src/app/node_modules

volumes:
  clientdependency: {}