name: Feature Terraform

on:
  pull_request:
    paths:
      - "terraform/**"
    branches:
      - main

jobs:
  init:
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.2.3
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
